export { default as B } from "./B";
export * from "./B";
export { default as H1 } from "./H1";
export * from "./H1";
export { default as H2 } from "./H2";
export * from "./H2";
export { default as H3 } from "./H3";
export * from "./H3";
export { default as H4 } from "./H4";
export * from "./H4";
export { default as H5 } from "./H5";
export * from "./H5";
export { default as H6 } from "./H6";
export * from "./H6";
export { default as Label } from "./Label";
export * from "./Label";
export { default as P } from "./P";
export * from "./P";
export { default as Span } from "./Span";
export * from "./Span";
